### ISSUE TITLE
FR:Variable border depending on the length of the text in description

### ISSUE THREAD

**Issue by kazdonkai** [nekoshita/obsidian-auto-card-link#15]
こんにちは。さっそく使ってみましたが，Obsidian の表現力が高まって良いですね。
そこでお願いなのですが，description が長い場合には，それに応じて，枠を大きくして全部を参照できるようにして欲しいです。
よろしくご検討ください。

**Comment by nekoshita** [comment]
ご意見ありがとうございます！
card-linkの見た目はCSSによって決定されているので、個別にカスタマイズしたい場合はCSS snippetsでCSSを上書きすることができます。
[こちらのドキュメント](https://help.obsidian.md/How+to/Add+custom+styles)を参考にCSS snippetsで以下のCSSを追加してもらうと、おそらくdescriptionが全部参照できるようになるかと！

```css
.auto-card-link-description {
    -webkit-line-clamp: unset !important;
    max-height: none !important;
}
```

**Comment by kazdonkai** [comment]
Snippet にCSS を登録しましたが，こんな感じになって上手く表示されていません
<img width="1090" alt="スクリーンショット 2022-04-23 14 28 35" src="https://user-images.githubusercontent.com/90127278/164879281-e018acf6-5878-43fc-8e17-d53427bd6068.png">
。

**Comment by nekoshita** [comment]
なるほど、そんなに長いdescriptionの場合もあるのですね💦
```css
.auto-card-link-card {
  height: none;
}
```
こちらをcss snippetsに追加すると縦幅120pxの制約がなくなるので、無限に縦に伸びるようにはなります。
しかし、それ以外の部分にどのような影響が出てくるのかは分からないので、他の部分でデザインが崩れる可能性があります。
